### ISSUE TITLE
Add Code to fold a linked list

### ISSUE THREAD

**Issue by user5047** [user5047/Repo_Hacktober#16]
Incase you are wondering, "what's a fold ?"

Reference - [Reference link](https://www.pepcoding.com/resources/online-java-foundation/linked-lists/fold-linkedlist-official/ojquestion)

**Comment by byahut007** [comment]
Please assign me I will do it in java

**Comment by user5047** [comment]
> Please assign me I will do it in java

Assigned buddy

**Comment by byahut007** [comment]
I'm very very sorry I haven't seen that

**Comment by byahut007** [comment]
I have created a pull request
