### ISSUE TITLE
Add code to find length of linked list

### ISSUE THREAD

**Issue by user5047** [user5047/Repo_Hacktober#6]

**Comment by Gneya** [comment]
Hey Can you please assign this issue to me. As I am a student and recently learned linkedlist so I think I can easily solve this problem in java

**Comment by user5047** [comment]
> Hey Can you please assign this issue to me. As I am a student and recently learned linkedlist so I think I can easily solve this problem in java

Alright, i'll assign this issue to you.

**Comment by Gneya** [comment]
Thank you.

**Comment by Gneya** [comment]
Please consider my PR

**Comment by user5047** [comment]
> Please consider my PR

Done
